# Generated by Django 5.1 on 2024-09-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat_openai", "0002_rename_openai_message_openaimessage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="openaimessage",
            old_name="text",
            new_name="content",
        ),
    ]
