# Generated by Django 5.1 on 2024-09-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_openai", "0003_rename_text_openaimessage_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="Messages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.TextField()),
                ("response", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
